In [1]:
import pandas as pd
import os

In [2]:
high_priority_insti = pd.read_csv('Upload_ Leads PHP(TESDA).csv')['Company'].to_list()

In [46]:
insti_df = pd.read_excel('filter_TVET_EDA_NCR_4A.xlsx', sheet_name='Clean Data')
insti_prov_map = dict(zip(insti_df['Institution Name'], insti_df['Province']))


leads_df = pd.read_excel('filter_TVET_EDA_NCR_4A.xlsx', 
                            sheet_name='Top Centers - 4A',
                            skiprows=4)
leads_df['Province'] = leads_df.Institution.map(insti_prov_map)
batangas_df = leads_df[leads_df.Province == 'Batangas'].copy()

batangas_df[['Institution', 'Quals', 'Trainers', 'Number of Yes', 'Enrolled', 'Graduates', 'Assessed', 'Certified', 'Decision']].sort_values(by='Graduates', ascending=False).head(20)

,Institution,Quals,Trainers,Number of Yes,Enrolled,Graduates,Assessed,Certified,Decision
21,SYNERGY ASSESSMENT & TRAINING CENTER,4.0,15.0,4.0,971.0,1034.0,0.0,0.0,3rd Priority
220,LE PRIME INSTITUTE OF TECHNOLOGY INC.,2.0,5.0,NaN,749.0,910.0,797.0,773.0,NaN
22,Regional Training Center - CALABARZON,18.0,22.0,5.0,715.0,871.0,0.0,0.0,Yes
25,EXCELSIOR CENTER FOR EXCELLENCE INC.,3.0,13.0,1.0,765.0,766.0,0.0,0.0,NaN
29,KAMELO MANPOWER SKILLS DEVELOPMENT CENTER INC.,4.0,11.0,4.0,595.0,737.0,0.0,0.0,3rd Priority
30,RUBIKS MANPOWER TRAINING CENTER INC.,5.0,12.0,1.0,711.0,716.0,1168.0,1141.0,NaN
31,Skillful Training and Assessment Center Inc.,3.0,7.0,0.0,594.0,715.0,0.0,0.0,NaN
35,GOALS TRAINING AND ASSESSMENT INSTITUTE INC.,5.0,11.0,1.0,741.0,681.0,0.0,0.0,NaN
36,"LEMERY COLLEGES, INC.",4.0,7.0,0.0,770.0,673.0,0.0,0.0,NaN
43,EQUINOX TRAINING CENTER INC.,5.0,7.0,0.0,505.0,560.0,155.0,156.0,NaN
148,DRIMSTECH TRAINING AND ASSESSMENT CENTER INC.,3.0,3.0,NaN,375.0,501.0,0.0,0.0,NaN
66,THE FORKS TRAINING AND ASSESSMENT SOLUTIONS INC.,5.0,5.0,1.0,374.0,403.0,1372.0,1279.0,2nd Priority
67,Provincial Training Center - Lipa,4.0,5.0,0.0,363.0,399.0,0.0,0.0,NaN
69,"BATANGAS EASTERN COLLEGES, INC.",9.0,10.0,4.0,734.0,362.0,530.0,504.0,Yes
75,BRIGHTWELL TECHNICAL EDUCATION TRAINING AND AS...,6.0,9.0,0.0,386.0,321.0,397.0,339.0,NaN
232,"CEN TECH - CENTER FOR TECHNICAL EXCELLENCE, INC.",2.0,4.0,NaN,237.0,283.0,0.0,0.0,NaN
106,FIRST IN LEARNING ELECTRONICS TRAINING CENTER,3.0,6.0,0.0,249.0,267.0,0.0,0.0,NaN
109,KUMINTANG INSTITUTE TRAINING AND ASSESSMENT INC.,4.0,5.0,0.0,264.0,261.0,329.0,347.0,NaN
111,"ST. PEREGRINE INSTITUTE, INC.",6.0,7.0,0.0,199.0,256.0,382.0,382.0,NaN
159,BEST MIND SKILLS TRAINING AND ASSESSMENT CENTE...,3.0,3.0,NaN,209.0,227.0,1208.0,1230.0,NaN

In [48]:
batangas_df[['Institution', 'Quals', 'Trainers', 'Number of Yes', 'Enrolled', 'Graduates', 'Assessed', 'Certified', 'Decision']].sort_values(by='Graduates', ascending=False).dropna(subset=['Decision']).head(20)

,Institution,Quals,Trainers,Number of Yes,Enrolled,Graduates,Assessed,Certified,Decision
21,SYNERGY ASSESSMENT & TRAINING CENTER,4.0,15.0,4.0,971.0,1034.0,0.0,0.0,3rd Priority
22,Regional Training Center - CALABARZON,18.0,22.0,5.0,715.0,871.0,0.0,0.0,Yes
29,KAMELO MANPOWER SKILLS DEVELOPMENT CENTER INC.,4.0,11.0,4.0,595.0,737.0,0.0,0.0,3rd Priority
66,THE FORKS TRAINING AND ASSESSMENT SOLUTIONS INC.,5.0,5.0,1.0,374.0,403.0,1372.0,1279.0,2nd Priority
69,"BATANGAS EASTERN COLLEGES, INC.",9.0,10.0,4.0,734.0,362.0,530.0,504.0,Yes